version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: devouch-discord-bot:latest
    container_name: devouch-discord-bot
    restart: unless-stopped
    env_file:
      - .env
    ports:
      # Health check endpoint
      - "8080:8080"
    volumes:
      # Mount for persistent logs
      - ./logs:/usr/src/app/logs
    networks:
      - bot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  bot-network:
    driver: bridge
